<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    protected $fillable = ['body', 'user_id'];

    public function question()
    {
        return $this->belongsTo(Question::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getBodyHtmlAttribute()
    {
        return \Parsedown::instance()->text($this->body);
    }

    public function getStatusAttribute()
    {
        return $this->isBest() ? 'vote_accepted' : '';
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($answer) {
            $answer->question->increment('answer_count');
        });

        static::deleted(function ($answer) {
            $answer->question->decrement('answer_count');
        });
    }

    function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    function getIsBestAttribute()
    {
        return $this->isBest();
    }

    public function isBest()
    {
        return $this->id == $this->question->best_answer_id;
    }
}
